# Generated by Django 4.1.4 on 2023-04-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_work_alter_project_managers_alter_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='content_es',
            field=models.TextField(null=True),
        ),
    ]
