# Generated by Django 4.1.4 on 2023-04-22 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_work_content_en_work_content_es'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='initial_date',
        ),
        migrations.AddField(
            model_name='work',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='work',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
