# Generated by Django 4.2 on 2023-05-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_work_initial_date_work_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
